services:
  # --- Databases ---
  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo_data:/data/db
    networks:
      - rag_net

  chroma:
    image: chromadb/chroma:0.5.3
    ports:
      - "8000:8000" #for development, remove in production
    volumes:
      - ./data/chroma_data:/chroma/chroma
    networks:
      - rag_net
    environment:
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]

  # --- Microservices ---
  retriever:
    build:  
      context: .
      dockerfile: ./services/retriever/Dockerfile
      args:
        EMBEDDING_MODEL_NAME: intfloat/multilingual-e5-large
        RERANK_MODEL_NAME: BAAI/bge-reranker-v2-m3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - CHROMA_HOST=chroma
      - ANONYMIZED_TELEMETRY=False
      - EMBEDDING_MODEL_NAME=intfloat/multilingual-e5-large
      - RERANK_MODEL_NAME=BAAI/bge-reranker-v2-m3
      - HYBRID_SEMANTIC_WEIGHT=0.6
      - HYBRID_BM25_WEIGHT=0.4
      - RETRIEVAL_K=15
      - RERANK_TOP_K=5
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=phonphai-phaser
    restart: unless-stopped     
    healthcheck:              
      test: ["CMD", "python", "-c", "import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(('localhost', 50051))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 500s
    networks:
      - rag_net

  agent:
    build: 
      context: .
      dockerfile: ./services/agent/Dockerfile
    environment:
      - RETRIEVER_HOST=retriever:50051
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ANONYMIZED_TELEMETRY=False
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=phonphai-agent
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(('localhost', 50052))"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      retriever:
        condition: service_healthy
    networks:
      - rag_net

  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    ports:
      - "8080:8000"
    environment:
      - AGENT_HOST=agent:50052
      - RETRIEVER_HOST=retriever:50051
    restart: unless-stopped      
    depends_on:
      retriever:
        condition: service_healthy
      agent:
        condition: service_healthy
    networks:
      - rag_net

networks:
  rag_net:
    driver: bridge