%%{init: {'theme': 'base', 'themeVariables': { 'doneTaskBkgColor': '#4CAF50', 'doneTaskBdrColor': '#388E3C', 'activeTaskBkgColor': '#FFC107', 'activeTaskBdrColor': '#FFA000', 'taskBkgColor': '#F44336', 'taskBdrColor': '#D32F2F', 'taskTextLightColor': '#FFFFFF', 'taskTextDarkColor': '#000000'}}}%%
gantt
    title Loop 2: Evaluation & Performance
    dateFormat YYYY-MM-DD
    axisFormat %m/%d
    tickInterval 1week
    todayMarker off
    
    
    Backend Implementation   :active, 2026-02-19, 2026-03-11
    User Evaluation (Pilot)  :        2026-03-11, 2026-03-18
    Full System Integration  :        2026-03-11, 2026-03-25
    System Testing           :        2026-03-19, 2026-03-25
    Pipeline Optimization    :        2026-03-19, 2026-03-25
