import json

import chatbot_pb2
import chatbot_pb2_grpc
from core.graph import app as langgraph_app
from langchain_core.messages import HumanMessage
from logger import log


def _format_ticket_lookup_message(ticket_lookups: list[dict]) -> str:
    blocks = []

    for lookup in ticket_lookups:
        ticket_code = lookup.get("ticket_code", "Unknown")
        rows = lookup.get("rows", [])
        if not rows:
            blocks.append(f"ไม่พบข้อมูลคำร้องหมายเลข {ticket_code}")
            continue

        first_row = rows[0]
        status = first_row.get("status") or "-"
        process_level = first_row.get("process_level") or "-"
        blocks.append(
            f"คำร้องหมายเลข {ticket_code} มีสถานะ {status} และมีการดำเนินการระดับ {process_level}"
        )

    return "\n\n".join(blocks)


class AgentServicer(chatbot_pb2_grpc.AgentServiceServicer):
    def Chat(self, request, context):
        log.info(f"🧠 Processing query: {request.user_message} (Session: {request.session_id})")

        # 1. Prepare Input for LangGraph
        initial_state = {"messages": [HumanMessage(content=request.user_message)]}

        # 2. Run the Graph
        final_state = langgraph_app.invoke(initial_state)
        final_message = final_state["messages"][-1]
        ai_text = final_message.content

        # 3. Extract sources generated by the formatter node
        source_items = final_state.get("final_sources", [])
        sources = [
            chatbot_pb2.Source(
                title=source.get("title", "Retrieved Document"),
                theme=source.get("theme", "Unknown Theme"),
                content=source.get("content", ""),
            )
            for source in source_items
        ]
        retrieved_chunks = final_state.get("retrieved_chunks", [])
        for chunk in retrieved_chunks:
            sources.append(
                chatbot_pb2.Source(
                    title=chunk.get("file_name", "Retrieved Chunk"),
                    theme="__retrieved_chunk__",
                    content=chunk.get("content", ""),
                )
            )
        ticket_lookups = final_state.get("ticket_lookup_results", [])
        if ticket_lookups:
            ai_text = _format_ticket_lookup_message(ticket_lookups)
            for lookup in ticket_lookups:
                sources.append(
                    chatbot_pb2.Source(
                        title=lookup.get("ticket_code", "Ticket Lookup"),
                        theme="ticket_lookup",
                        content=json.dumps(lookup.get("rows", []), ensure_ascii=False),
                    )
                )
        selected_tools = final_state.get("selected_tools", [])
        if selected_tools:
            sources.append(
                chatbot_pb2.Source(
                    title="__selected_tools__",
                    theme="__meta__",
                    content="|".join(selected_tools),
                )
            )

        cost = float(final_state.get("cost") or 0.0)

        # 4. Return correct fields based on your chatbot.proto
        return chatbot_pb2.ChatResponse(
            session_id=request.session_id,
            ai_message=ai_text,
            sources=sources,
            cost=cost,
        )
